# Generated by Django 5.2 on 2025-05-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("number_of_people", models.PositiveIntegerField()),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Room"),
                            ("deluxe", "Deluxe Room"),
                            ("family", "Family Room"),
                            ("executive_suite", "Executive Suite"),
                            ("presidential_suite", "Presidential Suite"),
                            ("honeymoon_suite", "Honeymoon Suite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "guest_type",
                    models.CharField(
                        choices=[
                            ("bachelors", "Bachelors"),
                            ("couple", "Couple"),
                            ("family", "Family"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
