# Generated by Django 5.2 on 2025-05-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="room_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
