# Generated by Django 5.2 on 2025-05-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_booking_room_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
