# Generated by Django 5.2 on 2025-05-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0005_remove_booking_booking_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="price",
        ),
    ]
