# Generated by Django 5.2 on 2025-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0006_remove_booking_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
