# Generated by Django 5.2 on 2025-05-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0007_booking_booking_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="booking",
            name="room_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("checked_out", "Checked Out"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
    ]
