# Generated by Django 5.2 on 2025-05-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0008_alter_booking_options_booking_room_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.RemoveField(
            model_name="booking",
            name="room_price",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="status",
        ),
    ]
