# Generated by Django 5.2 on 2025-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0009_alter_booking_options_remove_booking_room_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="number_of_people",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="booking",
            name="room_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
