# Generated by Django 5.2 on 2025-05-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0010_alter_booking_number_of_people_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="room_number",
        ),
    ]
