# Generated by Django 5.2 on 2025-06-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0011_remove_booking_gender_remove_booking_room_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Standard Room", "Standard Room"),
                    ("Deluxe Room", "Deluxe Room"),
                    ("Family Room", "Family Room"),
                    ("Executive Suite", "Executive Suite"),
                    ("Presidential Suite", "Presidential Suite"),
                    ("Honeymoon Suite", "Honeymoon Suite"),
                ],
                max_length=50,
            ),
        ),
    ]
